// 🎯 CSS Component Loader - Generated by css-component-split.js
const cssComponentMap = {
  "carousel": {
    "files": [
      "/css/slick.css",
      "/css/slick-theme.css"
    ],
    "components": [
      "Cars.jsx",
      "Testimonials.jsx",
      "RelatedCars.jsx"
    ],
    "size": "~25KB",
    "description": "CSS para carousels e sliders"
  },
  "animations": {
    "files": [
      "/css/animate.css",
      "/css/animations-lazy.css"
    ],
    "components": [
      "Hero.jsx",
      "About.jsx",
      "Cars.jsx"
    ],
    "size": "~15KB",
    "description": "CSS para animações e transições"
  },
  "gallery": {
    "files": [
      "/css/jquery.fancybox.min.css"
    ],
    "components": [
      "Single.jsx",
      "Gallery.jsx"
    ],
    "size": "~8KB",
    "description": "CSS para galerias de fotos"
  },
  "mobile-menu": {
    "files": [
      "/css/mmenu.css"
    ],
    "components": [
      "Header.jsx",
      "MobileMenu.jsx"
    ],
    "size": "~12KB",
    "description": "CSS para menu mobile"
  }
};

class DynamicCSSLoader {
  constructor() {
    this.loadedCSS = new Set();
    this.loadingPromises = new Map();
  }

  async loadComponentCSS(componentType) {
    if (!cssComponentMap[componentType]) {
      console.warn(`Component type '${componentType}' not found`);
      return;
    }

    const config = cssComponentMap[componentType];
    const promises = config.files.map(file => this.loadCSS(file));
    
    try {
      await Promise.allSettled(promises);
      console.log(`✅ ${componentType} CSS loaded (${config.size})`);
    } catch (error) {
      console.warn(`⚠️ Error loading ${componentType} CSS:`, error);
    }
  }

  async loadCSS(cssPath) {
    const id = cssPath.replace(/[^a-zA-Z0-9]/g, '-');
    
    if (this.loadedCSS.has(id) || document.getElementById(id)) {
      return Promise.resolve();
    }

    if (this.loadingPromises.has(id)) {
      return this.loadingPromises.get(id);
    }

    const promise = new Promise((resolve, reject) => {
      const link = document.createElement('link');
      link.rel = 'stylesheet';
      link.href = cssPath;
      link.id = id;
      
      link.onload = () => {
        this.loadedCSS.add(id);
        this.loadingPromises.delete(id);
        resolve();
      };
      
      link.onerror = () => {
        this.loadingPromises.delete(id);
        resolve(); // Don't reject - continue without CSS
      };

      document.head.appendChild(link);
    });

    this.loadingPromises.set(id, promise);
    return promise;
  }
}

// Export singleton
export const dynamicCSSLoader = new DynamicCSSLoader();